version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ramiro
      POSTGRES_PASSWORD: Htazzxs101
      POSTGRES_DB: dl_interactive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
